import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { PT_Serif } from 'next/font/google'
import { authOptions } from './(admin)/api/auth/[...nextauth]/route'
import { AuthProvider, LoadingComponent, NavbarAuthComponent, NavbarNotAuthComponent } from '@/component/export'
import { Suspense } from 'react'
import { ProviderStore } from '@/redux/provider'


const ptSerif=PT_Serif({
  weight:'400',subsets:['latin']
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session=await getServerSession(authOptions);
  return (
    <AuthProvider>
      <ProviderStore>
        <html lang="en">
          <body className={ptSerif.className}>
            {session?(
              <>
                <NavbarAuthComponent/>
                <Suspense fallback={<LoadingComponent/>}>{children}</Suspense>
              </>
            ):(
              <>
                <NavbarNotAuthComponent/>
                <Suspense fallback={<LoadingComponent/>}>{children}</Suspense>
              </>
            )}
          </body>
        </html>

      </ProviderStore>
    </AuthProvider>
  )
}
